Script started on Tue 21 Oct 2014 11:53:32 PM PDT
~
achao008@hammer $ cd ~/Documents/CS`00[K[K[K100/rshell/bin/[K/
~/Documents/CS100/rshell/bin
achao008@hammer $ rshell
rshell$ ls
rshell
rshell$ ls -a
execvp: No such file or directory
rshell$ ls  pwd
/home/csmajs/achao008/Documents/CS100/rshell/bin
rshell$ uptime
 23:54:21 up 16 days,  3:29, 63 users,  load average: 2.85, 2.73, 2.60
rshell$ ls -a   really lon     ylongparamt eter name
execvp: No such file or directory
rshell$ ls || ls
execvp: No such file or directory
rshell$ ls  || ls
execvp: No such file or directory
rshell$ ls ||ls
rshell
rshell$ pwd && pwd
execvp: No such file or directory
rshell$ pwd&& pwd
execvp: No such file or directory
rshell$ pwd &&pwd
/home/csmajs/achao008/Documents/CS100/rshell/bin
rshell$ pwd ; pwd
execvp: No such file or directory
rshell$ pwdl ; pwd
execvp: No such file or directory
rshell$ pwd ;pwd
/home/csmajs/achao008/Documents/CS100/rshell/bin
rshell$ git
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]

The most commonly used git commands are:
   add        Add file contents to the index
   bisect     Find by binary search the change that introduced a bug
   branch     List, create, or delete branches
   checkout   Checkout a branch or paths to the working tree
   clone      Clone a repository into a new directory
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   fetch      Download objects and refs from another repository
   grep       Print lines matching a pattern
   init       Create an empty git repository or reinitialize an existing one
   log        Show commit logs
   merge      Join two or more development histories together
   mv         Move or rename a file, a directory, or a symlink
   pull       Fetch from and merge with another repository or a local branch
   push       Update remote refs along with associated objects
   rebase     Forward-port local commits to the updated upstream head
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index
   show       Show various types of objects
   status     Show the working tree status
   tag        Create, list, delete or verify a tag object signed with GPG

See 'git help COMMAND' for more information on a specific command.
rshell$ git i status
execvp: No such file or directory
rshell$ exit
Exiting rshell.
~/Documents/CS100/rshell/bin
achao008@hammer $ exit
exit

Script done on Tue 21 Oct 2014 11:55:52 PM PDT
